#!/usr/bin/env node
'use strict';

/**
 * Builds public/icons.css from the icons the interface actually uses.
 *
 *   npm run build:icons
 *
 * Font Awesome was loaded whole, from cdnjs: 103 KB of CSS describing 1,392
 * icons and a 156 KB webfont, to draw the seventy this site draws. It also put
 * a third domain in front of the first paint and needed its own exception in
 * the Content-Security-Policy.
 *
 * This reads the markup, finds every `fa-*` class in it, and writes one rule
 * per icon carrying that icon's own path as a CSS mask. The class names are
 * unchanged, so no markup moves: `<i class="fa-solid fa-key">` keeps working,
 * still sized by `font-size` and still coloured by `color`, because a mask
 * paints in `currentColor`.
 *
 * Run it after adding an icon to the markup. `npm run build:css` runs it, so
 * the ordinary build and start scripts already do.
 */

const { readFileSync, writeFileSync, existsSync } = require('node:fs');
const { join } = require('node:path');

const ROOT = join(__dirname, '..');
const SOURCES = [join(ROOT, 'public', 'index.html'), join(ROOT, 'public', 'app.js')];
const SVG_ROOT = join(ROOT, 'node_modules', '@fortawesome', 'fontawesome-free', 'svgs');
const OUT = join(ROOT, 'public', 'icons.css');

/** Classes that share the `fa-` prefix but name a behaviour, not an icon. */
const NOT_ICONS = new Set(['solid', 'regular', 'brands', 'spin', 'li', 'fw']);

/** Where to look for an icon whose family the markup does not pin down. */
const FAMILIES = ['solid', 'regular', 'brands'];

function used() {
  const found = new Map();

  const register = (name, family) => {
    if (NOT_ICONS.has(name)) return;
    // First use wins. An icon drawn in two families would need two rules,
    // which has not happened and would be visible in the diff if it did.
    if (!found.has(name)) found.set(name, family);
  };

  for (const file of SOURCES) {
    const text = readFileSync(file, 'utf8');

    // Chunk first: a class attribute or a quoted string that mentions `fa-`.
    // The family is a sibling class, so it can only be read from the chunk the
    // icon sits in — `'fa-solid fa-eye-slash text-[13px]'` in app.js is as
    // much a class list as anything in the markup.
    const chunks = [
      ...text.matchAll(/class="([^"]*\bfa-[^"]*)"/g),
      ...text.matchAll(/'([^'\n]*\bfa-[^'\n]*)'/g),
      ...text.matchAll(/`([^`\n]*\bfa-[^`\n]*)`/g),
    ];

    for (const [, chunk] of chunks) {
      // Matched rather than split on whitespace: app.js builds markup inside
      // single-quoted strings, so a naive split yields `fa-star"></i></span>`
      // as an icon name.
      const classes = chunk.match(/\bfa-[a-z0-9-]+/g) || [];
      const family = classes.includes('fa-regular')
        ? 'regular'
        : classes.includes('fa-brands')
          ? 'brands'
          : 'solid';

      for (const cls of classes) register(cls.slice(3), family);
    }

    // Then anything the chunking missed — an icon name concatenated onto a
    // string, which is how half of app.js builds its rows. Solid is the right
    // default here: `dataUri` falls back through the other families if the
    // name is not in it, and 210 of the 212 uses on this site are solid.
    for (const [token] of text.matchAll(/\bfa-[a-z0-9-]+/g)) {
      register(token.slice(3), 'solid');
    }
  }

  return [...found.entries()].sort((a, b) => a[0].localeCompare(b[0]));
}

/**
 * One icon as a data URI.
 *
 * The SVG is stripped to the geometry a mask needs — a mask ignores fill, and
 * `fill="currentColor"` inside a masked image is meaningless anyway.
 */
function dataUri(name, family) {
  const preferred = [family, ...FAMILIES.filter((other) => other !== family)];

  for (const candidate of preferred) {
    const path = join(SVG_ROOT, candidate, `${name}.svg`);
    if (!existsSync(path)) continue;

    const svg = readFileSync(path, 'utf8')
      .replace(/<!--[\s\S]*?-->/g, '')
      .replace(/\s+/g, ' ')
      .trim();

    // Percent-encode only what a CSS url() token cannot carry unquoted.
    const encoded = svg
      .replace(/"/g, "'")
      .replace(/%/g, '%25')
      .replace(/#/g, '%23')
      .replace(/\{/g, '%7B')
      .replace(/\}/g, '%7D')
      .replace(/</g, '%3C')
      .replace(/>/g, '%3E');

    return { uri: `data:image/svg+xml,${encoded}`, family: candidate };
  }

  return null;
}

const icons = used();
const rules = [];
const missing = [];

for (const [name, family] of icons) {
  const resolved = dataUri(name, family);
  if (!resolved) {
    missing.push(name);
    continue;
  }
  rules.push(`.fa-${name}{-webkit-mask-image:url("${resolved.uri}");mask-image:url("${resolved.uri}")}`);
}

const css = `/* Generated by scripts/build-icons.js — do not edit.
 * ${rules.length} icons, built from the markup. Run \`npm run build:icons\`. */
.fa-solid,.fa-regular,.fa-brands{display:inline-block;width:1em;height:1em;background-color:currentColor;vertical-align:-0.125em;-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;-webkit-mask-position:center;mask-position:center;-webkit-mask-size:contain;mask-size:contain}
/* Font Awesome's own spinner, kept because the markup asks for it by name. */
@keyframes fa-spin{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}
.fa-spin{animation:fa-spin 2s linear infinite}
@media (prefers-reduced-motion:reduce){.fa-spin{animation-duration:10s}}
/* The bullet of a list that replaced its markers with icons. */
.fa-li{position:absolute;left:-1.75em;width:1.75em;text-align:center;line-height:inherit}
${rules.join('\n')}
`;

writeFileSync(OUT, css, 'utf8');

const bytes = Buffer.byteLength(css, 'utf8');
console.log(`icons.css: ${rules.length} icons, ${(bytes / 1024).toFixed(1)} KB`);
if (missing.length) {
  console.error(`Not found in Font Awesome: ${missing.join(', ')}`);
  process.exitCode = 1;
}
